### ISSUE TITLE
Syncbot: isn't marking public comments % in FlowDock

### ISSUE THREAD

**Issue by sonyagreen** [resin-io-modules/resin-procbots#361] opened 2017-12-07 19:50 UTC
Specimen: https://www.flowdock.com/app/rulemotion/public-s-premium/threads/xxcGbDymOClkMFoxRIfqZNPu-So

Annotated with blue asterisks, both the user's public comments and Juan's public comments do not have a %. Juan's public comments definitely should, so this is a bug. The user's comments I'm not sure - but my expectation was that they'd also show up as %.

![screen shot 2017-12-07 at 2 46 20 pm](https://user-images.githubusercontent.com/1054720/33735604-c1221b0c-db5d-11e7-875d-e67761d46551.png)

**Comment by sqweelygig** [comment] 2017-12-08 09:51
Duplicate of #357

**Closed by sqweelygig** 2017-12-08 09:51 UTC
