### ISSUE TITLE
VersionBot:  Check to ensure an approved review is by an approved reviewer

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#27] opened 2017-02-13 10:34 UTC
We've been discussing configuration of ProcBots for a while. We could then, in fact, have a `procbots.yml` file in the root of each repository and include the following section:
```
reviews:
    minimum_approves: 2
    maintainers:
        - hedss
        - lekkas
```
This would then allow, for example, VersionBot to determine that it can only merge when:
* At least one reviewer has approved the PR
* When **only** either 'hedss' or 'lekkas' has added the `procbots/versionbot/ready-to-merge` tag on the PR

**Comment by lurch** [comment] 2017-02-17 15:40
:+1: to a `procbots.yml` file - it's easy to imagine there'll be lots of things that'll need per-repo (and/or per-branch) configuration.

Given that the labels have been "name-spaced" as e.g. `procbots/versionbot/ready-to-merge`, I wonder if similar "name-spacing" should be used inside `procbots.yml`?

> `minimum_approves: 2` ... At least one reviewer has approved the PR

Huh, typo?

> When **only** either 'hedss' or 'lekkas' has added the `procbots/versionbot/ready-to-merge` tag on the PR

Should at least one of 'hedds' or 'lekkas' have approved the PR too? Or are you making that implicit within the action of them adding the `procbots/versionbot/ready-to-merge` label?  Given that the Github web interface doesn't make it clear who the last person to add a label was (without scrolling through the history of comments) I wonder if it might be better to keep it more explicit as 'at least one maintainer has approved the PR' ?
(but then I'm not that familiar with how labels are used on Github by resin.io, so maybe I'm missing something here? I guess I ought to go and read the associated HQ spec... ;)  )

**Comment by hedss** [comment] 2017-02-17 17:37
Yes, typo. :)

The assumption is that only one of them needs to have added the label. It doesn't make an assumption about who should review. We usually have many reviewers, but only one or two maintainers of a component.

@lekkas and I have talked at length about a config file, and I'd expect an extra section, such as:
```
reviewers:
  - Page-
  - lurch
  - lekkas
  - hedss
```
etc. for this. The beauty of this is VersionBot could (if we desire) also assign them all on PR open.
The GH API allows VersionBot to determine who has added labels, incidentally.

**Comment by lurch** [comment] 2017-02-17 20:29
Right, so (one of) the maintainers only needs to add the `procbots/versionbot/ready-to-merge` label, they don't need to have reviewed it too?
(just out of curiosity, does two people adding the same label get seen by the GH API as two people adding the same label, or as the second person removing the first person's label and then adding their own? IYSWIM)

Nice idea with the auto-assigned-default-reviewers :)
I wonder if one-possible-workflow might be for VersionBot to add the default reviewers, only if the PR doesn't have any reviewers assigned to it yet when the `flow/in-review` label gets added?
(again, apologies if I'm not quite understanding how labels get used)

**Comment by hedss** [comment] 2017-02-18 19:32
Labels are either applied or unapplied, you can't apply a label that isn't already applied, you can only cancel it.

Yeah, applying reviewers if none have been applied might be good, but then if there are approved reviewers yet none of the assigned reviewers are one of those, then it's a bit of a pointless PR! :)

**Comment by lurch** [comment] 2017-02-19 12:45
Apologies for my label-confusion questions...

> you can't apply a label that isn't already applied

Huh?! Did you typo "isn't" instead of "is" ?

What I meant was, given that you've said that the `procbots/versionbot/ready-to-merge` label has to have been added by a maintainer, and the Github API is able to tell you who added a label, if a non-maintainer adds the `procbots/versionbot/ready-to-merge` label, does the maintainer then have to remove the label (added by the non-maintainer) before re-adding the label, to convert it into a maintainer-added label? (I hope that question makes sense!)
If there are multiple maintainers on a project, is there an easy way (or in fact any way) for one of the maintainers to tell if the `procbots/versionbot/ready-to-merge` label was added by a fellow maintainer or by a non-maintainer? Or is this something where we need to rely on human discipline for the non-maintainers to not add the `procbots/versionbot/ready-to-merge` label? Or maybe VersionBot could automatically remove the `procbots/versionbot/ready-to-merge` label if it does get (mistakenly?) added by a non-maintainer user?
I realise this is a bit of a contrived question, but it's always good to figure out the expected behaviour in corner-cases ;-)

> applying reviewers if none have been applied might be good

I was imagining a scenario where you have e.g. 5 default reviewers on a project, but you happen to know that the PR you're submitting falls within only one reviewer's area of expertise, so you specifically ask for a review from that person, rather than letting VersionBot invite reviews from _all_ of the default reviewers (IYSWIM!)
Does your usage of the "approved reviewers" phrase imply that when checking against the `minimum_approves:` constraint, VersionBot will only count reviews from the people in the `reviewers:` list?
(and again, without memorising each repo's list of approved reviewers, I guess there's no way in the github webinterface to tell if a review is from an approved reviewer or not, so it might be difficult to tell that VersionBot isn't merging a PR because it has 3 reviews, but none of them are from the approved-reviewers list. Or perhaps I'm just over-complicating things and imagining corner-cases that'll never happen in reality :-/ )

**Comment by hedss** [comment] 2017-02-19 14:21
We have zero control over who can/cannot change labels on Github. This is an honour system, and if someone breaks the code then they can expect to get shouted at.

And yes, the `minimum_approves` would go hand in hand with the `reviewers` list, it'd have to. At the end of the day, if someone external adds a review as it's 'their area of expertise', the maintainer will still have to come along to add a merge label anyway, and they can approve at that point. Hell, they can even update the YAML file to add the new reviewer, so it instantly works. I don't think this is really a problem.

**Comment by lurch** [comment] 2017-02-20 13:47
Just to clarify, I was talking about the area-of-expertise of somebody already in the `reviewers` list, rather than an 'external reviewer'. (I was merely trying to 'minimise' the amount of notifications that get sent out, if the person submitting the PR knows in advance which one of the approved reviewers they want to target)


Thinking about the bot-separation discussion in #3 perhaps this issue should be implemented by a ReviewBot rather than VersionBot, and then it'd just be another status-check for VersionBot to look at? (or maybe for something so simple that's too-much separation?)

**Comment by hedss** [comment] 2017-02-20 13:56
It's simple, but that also relies on several bots being present for something not to go wrong. If you don't want a `ReviewBot` running, you still have to ensure maintainers/reviewers are authorised before merging. I'm extremely loathe to to dependencies on stateless bots.

**Comment by lekkas** [comment] 2017-02-21 11:50
I really like where this is going (automatically adding all reviewers from the config file, minimum approves from configured reviewers and all the rest of the cool stuff mentioned here). I don't have a strong opinion on whether this should be a separate bot but yeah, this looks like a process that the current version/merge bot should handle.

Also, I think that we can safely ignore having finer-grained settings on a per-PR level and keep the `procebot.yml` review settings for all submitted PRs (at least, until we get more feedback from the team and overriding settings on a PR level proves necessary but this looks like an overkill for me at the moment)

So a preliminary `procbots.yml` will look like

```yml
reviews:
    minimum_approves: 2
    maintainers:
      - hedss
      - lekkas
    reviewers:
      - Page-
      - lurch
      - petrosagg
      - emirotin
```

Reviewers/maintainers can be added/removed with simple PRs to the repo as @hedss mentioned.

**Comment by lurch** [comment] 2017-02-21 12:44
Presumably the people listed in `maintainers` are implicitly in the `reviewers` list too?
Oooh, there's an interesting thought - I guess if the PR has been authored by one of the reviewers, then any review they add themselves should be ignored when counting the `minimum_approves`?

If a `reviews:` section is present, are the `minimum_approves:`, `maintainers:` and `reviewers:` all compulsory properties (and if so, should VersionBot warn you if any are missing?), or could there be any scenarios in which it'd make sense to leave out one of the properties (and if so, how would that affect the behaviour?). Sorry if I'm jumping-the-gun again.

**Comment by lekkas** [comment] 2017-02-21 13:08
btw just saw that Hedss had already suggested a YAML structure before https://github.com/resin-io-modules/resin-procbots/issues/27#issuecomment-281321547 in https://github.com/resin-io-modules/resin-procbots/issues/45 so let's continue the discussion there

**Comment by lurch** [comment] 2017-02-21 13:19
IMHO #45 is about the YAML file / structure itself (i.e. at a generic level), whereas this PR is specifically about the `reviews:` section of the YAML?

**Comment by hedss** [comment] 2017-02-21 14:54
For the review section, let's keep it here for the moment.
@lurch I consider each of these proposed properties to be optional. They're all mutually exclusive but can be compounded to form a stricter PR process. There's no warning if any of them are missing. This configuration is purely down to the repo, which may or may not have individual tastes. The `ProcBot` should include in any error/resolved message configurations it's using, however.

**Comment by lurch** [comment] 2017-02-21 16:21
Just to be pedantic, "mutually exclusive" would mean that they _couldn't_ be used together, I suspect you meant they're independently usable? ;-P

To check I understand things (and to act as a starting point for any documentation) :
 * `minimum_approves` by itself = VersionBot will wait until there's that many approves (regardless of who they're from)
 * `maintainers` by itself _or_ with other properties = VersionBot will ignore any `procbots/versionbot/ready-to-merge` label that wasn't added by a maintainer
 * `reviewers` by itself = VersionBot will automatically ask for reviews from these people
 * `minimum_approves` in combination with `reviewers` = VersionBot will automatically ask for reviews from these people, and _only_ reviews from these people will count towards the `minimum_approves` total

If `reviewers` and `maintainers` are specified together, are the people in the maintainers list implicitly added to the reviewers list? i.e. automatically asked for reviews and / or included in the minimum_approves count. Or should they be explicitly separate with people needing to be listed in both `reviewers` and `maintainers` if they want to participate in both roles?

**Comment by hedss** [comment] 2017-02-21 19:21
I don't think it should be assumed the maintainers are also reviewers. We have people doing temporary maintainer roles atm who might not know the ins and outs. I can also see situations where maintainers essentially becomes a full time job doing the entire backend. Apart from that, the conclusions are correct.

**Comment by lurch** [comment] 2017-02-22 01:23
So, if `hedds` is in the maintainers list, but not in the reviewers list, then any reviews from `hedds` shouldn't count towards the `minimum_approves` total?

**Comment by hedss** [comment] 2017-02-22 08:43
@lurch Yup! The thinking behind it is some 'professional distance', although it's entirely feasible that someone could be in both lists (and in reality, probably will be!).

**Comment by lurch** [comment] 2017-02-22 12:34
Cool, I just wanted to get that clarified, in case people assumed the opposite :+1:

**Comment by hedss** [comment] 2017-03-22 09:50
@lekkas has pointed out using the Issues timeline includes reviews and their status, which would actually suit our purpose.

VB would have to get the entire list and do chronological matching to ensure that:
* Reviewers who had previously requested changes have now approved
* There are a minimum number of approves (if configured) and those approves come from approved reviewers (if configured)

We can then drop the `procbots/versionbot/ready-to-merge` label completely, which frees maintainers up from having to return to an issue to merge it.

**Comment by lekkas** [comment] 2017-03-22 10:33
> There are a minimum number of approves (if configured) and those approves come from approved reviewers (if configured)
> ...
> We can then drop the procbots/versionbot/ready-to-merge label completely

Even if If merges can happen automatically after a 'majority vote' / minimum approvals, I think that we should still provide PR authors/maintainers the tool to force a VB merge (i.e. merging + versioning + changelog update).

**Comment by lurch** [comment] 2017-03-22 13:37
I guess the `procbots/versionbot/ready-to-merge` label would also still be needed if a project chooses not to use the approved-reviewers thing?

And I guess in addition to "Reviewers who had previously requested changes have now approved" you'll also need to check for previously-approved reviews that have since been dismissed.

**Comment by hedss** [comment] 2017-04-11 09:29
![](https://github.trello.services/images/mini-trello-icon.png) [VersionBot: Check to ensure an approved review is by an approved reviewer](https://trello.com/c/ThBUe9ku/8-versionbot-check-to-ensure-an-approved-review-is-by-an-approved-reviewer)

**Comment by hedss** [comment] 2017-04-11 09:29
![](https://github.trello.services/images/mini-trello-icon.png) [VersionBot: Ensure that multi-status services used on protection branches are correctly handled](https://trello.com/c/Lqxmztbd/11-versionbot-ensure-that-multi-status-services-used-on-protection-branches-are-correctly-handled)

**Closed** 2017-07-24 12:21 UTC
Labels: enhancement, priority/high
